// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"gym-map/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCategory creates a new instance of MockCategory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategory {
	mock := &MockCategory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategory is an autogenerated mock type for the Category type
type MockCategory struct {
	mock.Mock
}

type MockCategory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategory) EXPECT() *MockCategory_Expecter {
	return &MockCategory_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockCategory
func (_mock *MockCategory) Delete(modelId int) error {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategory_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategory_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - modelId
func (_e *MockCategory_Expecter) Delete(modelId interface{}) *MockCategory_Delete_Call {
	return &MockCategory_Delete_Call{Call: _e.mock.On("Delete", modelId)}
}

func (_c *MockCategory_Delete_Call) Run(run func(modelId int)) *MockCategory_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockCategory_Delete_Call) Return(err error) *MockCategory_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategory_Delete_Call) RunAndReturn(run func(modelId int) error) *MockCategory_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCategory
func (_mock *MockCategory) Get() ([]model.Category, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []model.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Category, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Category); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategory_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCategory_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockCategory_Expecter) Get() *MockCategory_Get_Call {
	return &MockCategory_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockCategory_Get_Call) Run(run func()) *MockCategory_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCategory_Get_Call) Return(categorys []model.Category, err error) *MockCategory_Get_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockCategory_Get_Call) RunAndReturn(run func() ([]model.Category, error)) *MockCategory_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockCategory
func (_mock *MockCategory) GetById(modelId int) (model.Category, error) {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 model.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (model.Category, error)); ok {
		return returnFunc(modelId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) model.Category); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Get(0).(model.Category)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(modelId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategory_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockCategory_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - modelId
func (_e *MockCategory_Expecter) GetById(modelId interface{}) *MockCategory_GetById_Call {
	return &MockCategory_GetById_Call{Call: _e.mock.On("GetById", modelId)}
}

func (_c *MockCategory_GetById_Call) Run(run func(modelId int)) *MockCategory_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockCategory_GetById_Call) Return(model1 model.Category, err error) *MockCategory_GetById_Call {
	_c.Call.Return(model1, err)
	return _c
}

func (_c *MockCategory_GetById_Call) RunAndReturn(run func(modelId int) (model.Category, error)) *MockCategory_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockCategory
func (_mock *MockCategory) Insert(model1 *model.Category) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Category) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategory_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCategory_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - model1
func (_e *MockCategory_Expecter) Insert(model1 interface{}) *MockCategory_Insert_Call {
	return &MockCategory_Insert_Call{Call: _e.mock.On("Insert", model1)}
}

func (_c *MockCategory_Insert_Call) Run(run func(model1 *model.Category)) *MockCategory_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Category))
	})
	return _c
}

func (_c *MockCategory_Insert_Call) Return(err error) *MockCategory_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategory_Insert_Call) RunAndReturn(run func(model1 *model.Category) error) *MockCategory_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCategory
func (_mock *MockCategory) Update(model1 *model.Category) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Category) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategory_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategory_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - model1
func (_e *MockCategory_Expecter) Update(model1 interface{}) *MockCategory_Update_Call {
	return &MockCategory_Update_Call{Call: _e.mock.On("Update", model1)}
}

func (_c *MockCategory_Update_Call) Run(run func(model1 *model.Category)) *MockCategory_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Category))
	})
	return _c
}

func (_c *MockCategory_Update_Call) Return(err error) *MockCategory_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategory_Update_Call) RunAndReturn(run func(model1 *model.Category) error) *MockCategory_Update_Call {
	_c.Call.Return(run)
	return _c
}
