// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStoreBase creates a new instance of MockStoreBase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreBase[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreBase[T] {
	mock := &MockStoreBase[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoreBase is an autogenerated mock type for the StoreBase type
type MockStoreBase[T any] struct {
	mock.Mock
}

type MockStoreBase_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockStoreBase[T]) EXPECT() *MockStoreBase_Expecter[T] {
	return &MockStoreBase_Expecter[T]{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockStoreBase
func (_mock *MockStoreBase[T]) Delete(modelId int) error {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoreBase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStoreBase_Delete_Call[T any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - modelId
func (_e *MockStoreBase_Expecter[T]) Delete(modelId interface{}) *MockStoreBase_Delete_Call[T] {
	return &MockStoreBase_Delete_Call[T]{Call: _e.mock.On("Delete", modelId)}
}

func (_c *MockStoreBase_Delete_Call[T]) Run(run func(modelId int)) *MockStoreBase_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockStoreBase_Delete_Call[T]) Return(err error) *MockStoreBase_Delete_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoreBase_Delete_Call[T]) RunAndReturn(run func(modelId int) error) *MockStoreBase_Delete_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockStoreBase
func (_mock *MockStoreBase[T]) Get() ([]T, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]T, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreBase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStoreBase_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockStoreBase_Expecter[T]) Get() *MockStoreBase_Get_Call[T] {
	return &MockStoreBase_Get_Call[T]{Call: _e.mock.On("Get")}
}

func (_c *MockStoreBase_Get_Call[T]) Run(run func()) *MockStoreBase_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStoreBase_Get_Call[T]) Return(vs []T, err error) *MockStoreBase_Get_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockStoreBase_Get_Call[T]) RunAndReturn(run func() ([]T, error)) *MockStoreBase_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockStoreBase
func (_mock *MockStoreBase[T]) GetById(modelId int) (T, error) {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (T, error)); ok {
		return returnFunc(modelId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) T); ok {
		r0 = returnFunc(modelId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(modelId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreBase_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockStoreBase_GetById_Call[T any] struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - modelId
func (_e *MockStoreBase_Expecter[T]) GetById(modelId interface{}) *MockStoreBase_GetById_Call[T] {
	return &MockStoreBase_GetById_Call[T]{Call: _e.mock.On("GetById", modelId)}
}

func (_c *MockStoreBase_GetById_Call[T]) Run(run func(modelId int)) *MockStoreBase_GetById_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockStoreBase_GetById_Call[T]) Return(model T, err error) *MockStoreBase_GetById_Call[T] {
	_c.Call.Return(model, err)
	return _c
}

func (_c *MockStoreBase_GetById_Call[T]) RunAndReturn(run func(modelId int) (T, error)) *MockStoreBase_GetById_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetManyByIds provides a mock function for the type MockStoreBase
func (_mock *MockStoreBase[T]) GetManyByIds(modelIds []int) ([]T, error) {
	ret := _mock.Called(modelIds)

	if len(ret) == 0 {
		panic("no return value specified for GetManyByIds")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int) ([]T, error)); ok {
		return returnFunc(modelIds)
	}
	if returnFunc, ok := ret.Get(0).(func([]int) []T); ok {
		r0 = returnFunc(modelIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int) error); ok {
		r1 = returnFunc(modelIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreBase_GetManyByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManyByIds'
type MockStoreBase_GetManyByIds_Call[T any] struct {
	*mock.Call
}

// GetManyByIds is a helper method to define mock.On call
//   - modelIds
func (_e *MockStoreBase_Expecter[T]) GetManyByIds(modelIds interface{}) *MockStoreBase_GetManyByIds_Call[T] {
	return &MockStoreBase_GetManyByIds_Call[T]{Call: _e.mock.On("GetManyByIds", modelIds)}
}

func (_c *MockStoreBase_GetManyByIds_Call[T]) Run(run func(modelIds []int)) *MockStoreBase_GetManyByIds_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]int))
	})
	return _c
}

func (_c *MockStoreBase_GetManyByIds_Call[T]) Return(models []T, err error) *MockStoreBase_GetManyByIds_Call[T] {
	_c.Call.Return(models, err)
	return _c
}

func (_c *MockStoreBase_GetManyByIds_Call[T]) RunAndReturn(run func(modelIds []int) ([]T, error)) *MockStoreBase_GetManyByIds_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockStoreBase
func (_mock *MockStoreBase[T]) Insert(model *T) error {
	ret := _mock.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*T) error); ok {
		r0 = returnFunc(model)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoreBase_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockStoreBase_Insert_Call[T any] struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - model
func (_e *MockStoreBase_Expecter[T]) Insert(model interface{}) *MockStoreBase_Insert_Call[T] {
	return &MockStoreBase_Insert_Call[T]{Call: _e.mock.On("Insert", model)}
}

func (_c *MockStoreBase_Insert_Call[T]) Run(run func(model *T)) *MockStoreBase_Insert_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*T))
	})
	return _c
}

func (_c *MockStoreBase_Insert_Call[T]) Return(err error) *MockStoreBase_Insert_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoreBase_Insert_Call[T]) RunAndReturn(run func(model *T) error) *MockStoreBase_Insert_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStoreBase
func (_mock *MockStoreBase[T]) Update(model *T) error {
	ret := _mock.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*T) error); ok {
		r0 = returnFunc(model)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoreBase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStoreBase_Update_Call[T any] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - model
func (_e *MockStoreBase_Expecter[T]) Update(model interface{}) *MockStoreBase_Update_Call[T] {
	return &MockStoreBase_Update_Call[T]{Call: _e.mock.On("Update", model)}
}

func (_c *MockStoreBase_Update_Call[T]) Run(run func(model *T)) *MockStoreBase_Update_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*T))
	})
	return _c
}

func (_c *MockStoreBase_Update_Call[T]) Return(err error) *MockStoreBase_Update_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoreBase_Update_Call[T]) RunAndReturn(run func(model *T) error) *MockStoreBase_Update_Call[T] {
	_c.Call.Return(run)
	return _c
}
