// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"gym-map/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMedia creates a new instance of MockMedia. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMedia(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMedia {
	mock := &MockMedia{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMedia is an autogenerated mock type for the Media type
type MockMedia struct {
	mock.Mock
}

type MockMedia_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMedia) EXPECT() *MockMedia_Expecter {
	return &MockMedia_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockMedia
func (_mock *MockMedia) Delete(modelId int) error {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMedia_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMedia_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - modelId
func (_e *MockMedia_Expecter) Delete(modelId interface{}) *MockMedia_Delete_Call {
	return &MockMedia_Delete_Call{Call: _e.mock.On("Delete", modelId)}
}

func (_c *MockMedia_Delete_Call) Run(run func(modelId int)) *MockMedia_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockMedia_Delete_Call) Return(err error) *MockMedia_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMedia_Delete_Call) RunAndReturn(run func(modelId int) error) *MockMedia_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockMedia
func (_mock *MockMedia) Get() ([]model.Media, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []model.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Media, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Media); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMedia_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMedia_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockMedia_Expecter) Get() *MockMedia_Get_Call {
	return &MockMedia_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockMedia_Get_Call) Run(run func()) *MockMedia_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMedia_Get_Call) Return(medias []model.Media, err error) *MockMedia_Get_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockMedia_Get_Call) RunAndReturn(run func() ([]model.Media, error)) *MockMedia_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockMedia
func (_mock *MockMedia) GetById(modelId int) (model.Media, error) {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 model.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (model.Media, error)); ok {
		return returnFunc(modelId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) model.Media); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Get(0).(model.Media)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(modelId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMedia_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockMedia_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - modelId
func (_e *MockMedia_Expecter) GetById(modelId interface{}) *MockMedia_GetById_Call {
	return &MockMedia_GetById_Call{Call: _e.mock.On("GetById", modelId)}
}

func (_c *MockMedia_GetById_Call) Run(run func(modelId int)) *MockMedia_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockMedia_GetById_Call) Return(model1 model.Media, err error) *MockMedia_GetById_Call {
	_c.Call.Return(model1, err)
	return _c
}

func (_c *MockMedia_GetById_Call) RunAndReturn(run func(modelId int) (model.Media, error)) *MockMedia_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIds provides a mock function for the type MockMedia
func (_mock *MockMedia) GetByIds(ids []int) ([]model.Media, error) {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIds")
	}

	var r0 []model.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int) ([]model.Media, error)); ok {
		return returnFunc(ids)
	}
	if returnFunc, ok := ret.Get(0).(func([]int) []model.Media); ok {
		r0 = returnFunc(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int) error); ok {
		r1 = returnFunc(ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMedia_GetByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIds'
type MockMedia_GetByIds_Call struct {
	*mock.Call
}

// GetByIds is a helper method to define mock.On call
//   - ids
func (_e *MockMedia_Expecter) GetByIds(ids interface{}) *MockMedia_GetByIds_Call {
	return &MockMedia_GetByIds_Call{Call: _e.mock.On("GetByIds", ids)}
}

func (_c *MockMedia_GetByIds_Call) Run(run func(ids []int)) *MockMedia_GetByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]int))
	})
	return _c
}

func (_c *MockMedia_GetByIds_Call) Return(medias []model.Media, err error) *MockMedia_GetByIds_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockMedia_GetByIds_Call) RunAndReturn(run func(ids []int) ([]model.Media, error)) *MockMedia_GetByIds_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockMedia
func (_mock *MockMedia) Insert(model1 *model.Media) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Media) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMedia_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockMedia_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - model1
func (_e *MockMedia_Expecter) Insert(model1 interface{}) *MockMedia_Insert_Call {
	return &MockMedia_Insert_Call{Call: _e.mock.On("Insert", model1)}
}

func (_c *MockMedia_Insert_Call) Run(run func(model1 *model.Media)) *MockMedia_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Media))
	})
	return _c
}

func (_c *MockMedia_Insert_Call) Return(err error) *MockMedia_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMedia_Insert_Call) RunAndReturn(run func(model1 *model.Media) error) *MockMedia_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockMedia
func (_mock *MockMedia) Update(model1 *model.Media) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Media) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMedia_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMedia_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - model1
func (_e *MockMedia_Expecter) Update(model1 interface{}) *MockMedia_Update_Call {
	return &MockMedia_Update_Call{Call: _e.mock.On("Update", model1)}
}

func (_c *MockMedia_Update_Call) Run(run func(model1 *model.Media)) *MockMedia_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Media))
	})
	return _c
}

func (_c *MockMedia_Update_Call) Return(err error) *MockMedia_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMedia_Update_Call) RunAndReturn(run func(model1 *model.Media) error) *MockMedia_Update_Call {
	_c.Call.Return(run)
	return _c
}
