// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"gym-map/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProperty creates a new instance of MockProperty. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProperty(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProperty {
	mock := &MockProperty{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProperty is an autogenerated mock type for the Property type
type MockProperty struct {
	mock.Mock
}

type MockProperty_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProperty) EXPECT() *MockProperty_Expecter {
	return &MockProperty_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockProperty
func (_mock *MockProperty) Delete(modelId int) error {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProperty_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProperty_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - modelId
func (_e *MockProperty_Expecter) Delete(modelId interface{}) *MockProperty_Delete_Call {
	return &MockProperty_Delete_Call{Call: _e.mock.On("Delete", modelId)}
}

func (_c *MockProperty_Delete_Call) Run(run func(modelId int)) *MockProperty_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockProperty_Delete_Call) Return(err error) *MockProperty_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProperty_Delete_Call) RunAndReturn(run func(modelId int) error) *MockProperty_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockProperty
func (_mock *MockProperty) Get() ([]model.Property, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []model.Property
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Property, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Property); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Property)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProperty_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProperty_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockProperty_Expecter) Get() *MockProperty_Get_Call {
	return &MockProperty_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockProperty_Get_Call) Run(run func()) *MockProperty_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProperty_Get_Call) Return(propertys []model.Property, err error) *MockProperty_Get_Call {
	_c.Call.Return(propertys, err)
	return _c
}

func (_c *MockProperty_Get_Call) RunAndReturn(run func() ([]model.Property, error)) *MockProperty_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockProperty
func (_mock *MockProperty) GetById(modelId int) (model.Property, error) {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 model.Property
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (model.Property, error)); ok {
		return returnFunc(modelId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) model.Property); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Get(0).(model.Property)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(modelId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProperty_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockProperty_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - modelId
func (_e *MockProperty_Expecter) GetById(modelId interface{}) *MockProperty_GetById_Call {
	return &MockProperty_GetById_Call{Call: _e.mock.On("GetById", modelId)}
}

func (_c *MockProperty_GetById_Call) Run(run func(modelId int)) *MockProperty_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockProperty_GetById_Call) Return(model1 model.Property, err error) *MockProperty_GetById_Call {
	_c.Call.Return(model1, err)
	return _c
}

func (_c *MockProperty_GetById_Call) RunAndReturn(run func(modelId int) (model.Property, error)) *MockProperty_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetManyByIds provides a mock function for the type MockProperty
func (_mock *MockProperty) GetManyByIds(modelIds []int) ([]model.Property, error) {
	ret := _mock.Called(modelIds)

	if len(ret) == 0 {
		panic("no return value specified for GetManyByIds")
	}

	var r0 []model.Property
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int) ([]model.Property, error)); ok {
		return returnFunc(modelIds)
	}
	if returnFunc, ok := ret.Get(0).(func([]int) []model.Property); ok {
		r0 = returnFunc(modelIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Property)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int) error); ok {
		r1 = returnFunc(modelIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProperty_GetManyByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManyByIds'
type MockProperty_GetManyByIds_Call struct {
	*mock.Call
}

// GetManyByIds is a helper method to define mock.On call
//   - modelIds
func (_e *MockProperty_Expecter) GetManyByIds(modelIds interface{}) *MockProperty_GetManyByIds_Call {
	return &MockProperty_GetManyByIds_Call{Call: _e.mock.On("GetManyByIds", modelIds)}
}

func (_c *MockProperty_GetManyByIds_Call) Run(run func(modelIds []int)) *MockProperty_GetManyByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]int))
	})
	return _c
}

func (_c *MockProperty_GetManyByIds_Call) Return(models []model.Property, err error) *MockProperty_GetManyByIds_Call {
	_c.Call.Return(models, err)
	return _c
}

func (_c *MockProperty_GetManyByIds_Call) RunAndReturn(run func(modelIds []int) ([]model.Property, error)) *MockProperty_GetManyByIds_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockProperty
func (_mock *MockProperty) Insert(model1 *model.Property) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Property) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProperty_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockProperty_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - model1
func (_e *MockProperty_Expecter) Insert(model1 interface{}) *MockProperty_Insert_Call {
	return &MockProperty_Insert_Call{Call: _e.mock.On("Insert", model1)}
}

func (_c *MockProperty_Insert_Call) Run(run func(model1 *model.Property)) *MockProperty_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Property))
	})
	return _c
}

func (_c *MockProperty_Insert_Call) Return(err error) *MockProperty_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProperty_Insert_Call) RunAndReturn(run func(model1 *model.Property) error) *MockProperty_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProperty
func (_mock *MockProperty) Update(model1 *model.Property) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Property) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProperty_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProperty_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - model1
func (_e *MockProperty_Expecter) Update(model1 interface{}) *MockProperty_Update_Call {
	return &MockProperty_Update_Call{Call: _e.mock.On("Update", model1)}
}

func (_c *MockProperty_Update_Call) Run(run func(model1 *model.Property)) *MockProperty_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Property))
	})
	return _c
}

func (_c *MockProperty_Update_Call) Return(err error) *MockProperty_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProperty_Update_Call) RunAndReturn(run func(model1 *model.Property) error) *MockProperty_Update_Call {
	_c.Call.Return(run)
	return _c
}
