// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"gym-map/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExercise creates a new instance of MockExercise. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExercise(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExercise {
	mock := &MockExercise{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExercise is an autogenerated mock type for the Exercise type
type MockExercise struct {
	mock.Mock
}

type MockExercise_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExercise) EXPECT() *MockExercise_Expecter {
	return &MockExercise_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockExercise
func (_mock *MockExercise) Delete(modelId int) error {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExercise_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockExercise_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - modelId
func (_e *MockExercise_Expecter) Delete(modelId interface{}) *MockExercise_Delete_Call {
	return &MockExercise_Delete_Call{Call: _e.mock.On("Delete", modelId)}
}

func (_c *MockExercise_Delete_Call) Run(run func(modelId int)) *MockExercise_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockExercise_Delete_Call) Return(err error) *MockExercise_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExercise_Delete_Call) RunAndReturn(run func(modelId int) error) *MockExercise_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockExercise
func (_mock *MockExercise) Get() ([]model.Exercise, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []model.Exercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Exercise, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Exercise); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Exercise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExercise_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockExercise_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockExercise_Expecter) Get() *MockExercise_Get_Call {
	return &MockExercise_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockExercise_Get_Call) Run(run func()) *MockExercise_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExercise_Get_Call) Return(exercises []model.Exercise, err error) *MockExercise_Get_Call {
	_c.Call.Return(exercises, err)
	return _c
}

func (_c *MockExercise_Get_Call) RunAndReturn(run func() ([]model.Exercise, error)) *MockExercise_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockExercise
func (_mock *MockExercise) GetById(modelId int) (model.Exercise, error) {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 model.Exercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (model.Exercise, error)); ok {
		return returnFunc(modelId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) model.Exercise); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Get(0).(model.Exercise)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(modelId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExercise_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockExercise_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - modelId
func (_e *MockExercise_Expecter) GetById(modelId interface{}) *MockExercise_GetById_Call {
	return &MockExercise_GetById_Call{Call: _e.mock.On("GetById", modelId)}
}

func (_c *MockExercise_GetById_Call) Run(run func(modelId int)) *MockExercise_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockExercise_GetById_Call) Return(model1 model.Exercise, err error) *MockExercise_GetById_Call {
	_c.Call.Return(model1, err)
	return _c
}

func (_c *MockExercise_GetById_Call) RunAndReturn(run func(modelId int) (model.Exercise, error)) *MockExercise_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByMachineId provides a mock function for the type MockExercise
func (_mock *MockExercise) GetByMachineId(machineId int) ([]model.Exercise, error) {
	ret := _mock.Called(machineId)

	if len(ret) == 0 {
		panic("no return value specified for GetByMachineId")
	}

	var r0 []model.Exercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]model.Exercise, error)); ok {
		return returnFunc(machineId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []model.Exercise); ok {
		r0 = returnFunc(machineId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Exercise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(machineId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExercise_GetByMachineId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByMachineId'
type MockExercise_GetByMachineId_Call struct {
	*mock.Call
}

// GetByMachineId is a helper method to define mock.On call
//   - machineId
func (_e *MockExercise_Expecter) GetByMachineId(machineId interface{}) *MockExercise_GetByMachineId_Call {
	return &MockExercise_GetByMachineId_Call{Call: _e.mock.On("GetByMachineId", machineId)}
}

func (_c *MockExercise_GetByMachineId_Call) Run(run func(machineId int)) *MockExercise_GetByMachineId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockExercise_GetByMachineId_Call) Return(exercises []model.Exercise, err error) *MockExercise_GetByMachineId_Call {
	_c.Call.Return(exercises, err)
	return _c
}

func (_c *MockExercise_GetByMachineId_Call) RunAndReturn(run func(machineId int) ([]model.Exercise, error)) *MockExercise_GetByMachineId_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithCount provides a mock function for the type MockExercise
func (_mock *MockExercise) GetWithCount() ([]model.ExerciseWithCount, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWithCount")
	}

	var r0 []model.ExerciseWithCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.ExerciseWithCount, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.ExerciseWithCount); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ExerciseWithCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExercise_GetWithCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithCount'
type MockExercise_GetWithCount_Call struct {
	*mock.Call
}

// GetWithCount is a helper method to define mock.On call
func (_e *MockExercise_Expecter) GetWithCount() *MockExercise_GetWithCount_Call {
	return &MockExercise_GetWithCount_Call{Call: _e.mock.On("GetWithCount")}
}

func (_c *MockExercise_GetWithCount_Call) Run(run func()) *MockExercise_GetWithCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExercise_GetWithCount_Call) Return(exercises []model.ExerciseWithCount, err error) *MockExercise_GetWithCount_Call {
	_c.Call.Return(exercises, err)
	return _c
}

func (_c *MockExercise_GetWithCount_Call) RunAndReturn(run func() ([]model.ExerciseWithCount, error)) *MockExercise_GetWithCount_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockExercise
func (_mock *MockExercise) Insert(model1 *model.Exercise) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Exercise) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExercise_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockExercise_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - model1
func (_e *MockExercise_Expecter) Insert(model1 interface{}) *MockExercise_Insert_Call {
	return &MockExercise_Insert_Call{Call: _e.mock.On("Insert", model1)}
}

func (_c *MockExercise_Insert_Call) Run(run func(model1 *model.Exercise)) *MockExercise_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Exercise))
	})
	return _c
}

func (_c *MockExercise_Insert_Call) Return(err error) *MockExercise_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExercise_Insert_Call) RunAndReturn(run func(model1 *model.Exercise) error) *MockExercise_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockExercise
func (_mock *MockExercise) Update(model1 *model.Exercise) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Exercise) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExercise_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExercise_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - model1
func (_e *MockExercise_Expecter) Update(model1 interface{}) *MockExercise_Update_Call {
	return &MockExercise_Update_Call{Call: _e.mock.On("Update", model1)}
}

func (_c *MockExercise_Update_Call) Run(run func(model1 *model.Exercise)) *MockExercise_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Exercise))
	})
	return _c
}

func (_c *MockExercise_Update_Call) Return(err error) *MockExercise_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExercise_Update_Call) RunAndReturn(run func(model1 *model.Exercise) error) *MockExercise_Update_Call {
	_c.Call.Return(run)
	return _c
}
